# Generated by Django 5.1.2 on 2025-11-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, unique=True)),
                ('date', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('budget', models.CharField(max_length=100)),
            ],
        ),
    ]
