# Generated by Django 5.1.2 on 2025-11-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie_review',
        ),
    ]
