# Generated by Django 5.1.2 on 2025-12-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
